/**
 * Notification preferences, in two halves.
 *
 * DEVICE-LOCAL (localStorage): build alerts and the weekly permission
 * reminder. Deliberately per-device - an operator may want OS-level build
 * alerts on their office desktop but not on a shared floor tablet, and
 * browser notification permission is itself per-device, so a reminder to
 * turn it on has to be per-device to mean anything.
 *
 * ACCOUNT-LEVEL (user_notification_preferences): whether pick tickets ring,
 * whether put-away batches notify, and whether pick-ticket email is sent.
 * Those follow the person across devices, and the email flag has to be
 * readable by the server when it builds a recipient list.
 */

import { supabase } from "@/integrations/supabase/client";

const BUILD_NOTIFICATIONS_KEY = "warehouseWizard.notifications.buildAlerts";

export function isBuildNotificationEnabled(): boolean {
  if (typeof window === "undefined") return false;
  try {
    // Default on — permission is still the real gate.
    return window.localStorage.getItem(BUILD_NOTIFICATIONS_KEY) !== "off";
  } catch {
    return true;
  }
}

export function setBuildNotificationEnabled(enabled: boolean) {
  if (typeof window === "undefined") return;
  try {
    window.localStorage.setItem(BUILD_NOTIFICATIONS_KEY, enabled ? "on" : "off");
  } catch {
    // Storage unavailable — preference simply won't persist on this device.
  }
}

// ---------------------------------------------------------------------------
// Weekly permission reminder (device-local)
// ---------------------------------------------------------------------------

const PERMISSION_NAG_KEY = "warehouseWizard.notifications.permissionNagShownAt";
const PERMISSION_NAG_INTERVAL_MS = 7 * 24 * 60 * 60 * 1000;

function nagKeyFor(userId: string | null | undefined): string {
  // Floor tablets are shared, so the throttle is keyed per user per device:
  // one person dismissing it must not silence it for the next shift.
  return `${PERMISSION_NAG_KEY}.${userId ?? "anonymous"}`;
}

/**
 * Whether the notification bell should carry a "turn notifications on" item.
 *
 * Returns false when permission is already granted - the weekly check exists
 * precisely so that the granted case costs nothing and says nothing. Only the
 * bell ever surfaces this: no toast, no banner.
 */
export function shouldRemindAboutNotifications(
  permission: string,
  userId: string | null | undefined,
  now: number = Date.now(),
): boolean {
  if (typeof window === "undefined") return false;
  if (permission === "granted" || permission === "unsupported") return false;
  try {
    const raw = window.localStorage.getItem(nagKeyFor(userId));
    if (!raw) return true;
    const shownAt = Number(raw);
    if (!Number.isFinite(shownAt)) return true;
    return now - shownAt >= PERMISSION_NAG_INTERVAL_MS;
  } catch {
    // Storage unavailable - better to remind than to go silent forever.
    return true;
  }
}

/** Start the next seven-day window. */
export function markNotificationReminderShown(userId: string | null | undefined, now: number = Date.now()) {
  if (typeof window === "undefined") return;
  try {
    window.localStorage.setItem(nagKeyFor(userId), String(now));
  } catch {
    // Preference simply will not persist on this device.
  }
}

// ---------------------------------------------------------------------------
// Account-level preferences (user_notification_preferences)
// ---------------------------------------------------------------------------

const PREFS_TABLE = "user_notification_preferences";

/**
 * types.ts is regenerated by the Lovable toolchain, so a table added by a
 * hand-written migration is not in it. Same escape hatch as
 * mobile-toolbar-preferences.ts.
 */
const prefsDb = supabase.from.bind(supabase) as (table: string) => any;

/** True while the migration has not been deployed yet - callers fall back to defaults. */
function isMissingPreferenceTable(error: unknown) {
  if (!error || typeof error !== "object") return false;
  const value = error as { code?: string; message?: string };
  return (value.code === "PGRST205" || value.code === "42P01") && (value.message ?? "").includes(PREFS_TABLE);
}

export type AccountNotificationPreferences = {
  /** Whether a released pick ticket rings on this account's devices. */
  pickListRing: boolean;
  /** Whether put-away batches raise their (silent) notification. */
  putawayBadge: boolean;
  /** Whether pick-ticket email is sent. A hard unsubscribe still wins. */
  emailPickList: boolean;
};

export const DEFAULT_ACCOUNT_NOTIFICATION_PREFERENCES: AccountNotificationPreferences = {
  pickListRing: true,
  putawayBadge: true,
  emailPickList: true,
};

export async function loadAccountNotificationPreferences(
  userId: string,
): Promise<AccountNotificationPreferences> {
  const { data, error } = await prefsDb(PREFS_TABLE)
    .select("pick_list_ring, putaway_badge, email_pick_list")
    .eq("user_id", userId)
    .maybeSingle();
  if (isMissingPreferenceTable(error)) return DEFAULT_ACCOUNT_NOTIFICATION_PREFERENCES;
  if (error) throw error;
  if (!data) return DEFAULT_ACCOUNT_NOTIFICATION_PREFERENCES;
  return {
    pickListRing: data.pick_list_ring !== false,
    putawayBadge: data.putaway_badge !== false,
    emailPickList: data.email_pick_list !== false,
  };
}

export async function saveAccountNotificationPreferences(
  userId: string,
  values: Partial<AccountNotificationPreferences>,
): Promise<void> {
  const payload: Record<string, unknown> = { user_id: userId, updated_at: new Date().toISOString() };
  if (values.pickListRing !== undefined) payload.pick_list_ring = values.pickListRing;
  if (values.putawayBadge !== undefined) payload.putaway_badge = values.putawayBadge;
  if (values.emailPickList !== undefined) payload.email_pick_list = values.emailPickList;

  const { error } = await prefsDb(PREFS_TABLE).upsert(payload, { onConflict: "user_id" });
  if (isMissingPreferenceTable(error)) return;
  if (error) throw error;
}
