/**
 * Web Push subscription lifecycle for this device.
 *
 * The VAPID public key is fetched at runtime from the push-notify edge
 * function rather than read from a build-time env var, because .env is
 * generated by the Lovable toolchain and must not be hand-edited. It also
 * means the public and private halves cannot drift: both come from the same
 * Supabase secrets.
 *
 * ensurePushSubscription() must stay idempotent and run on every app boot.
 * src/main.tsx purges and unregisters service workers on a version change, the
 * preview-host branch unregisters unconditionally, and release-policy.ts does
 * the same on a forced update — each of which destroys the push subscription,
 * because that state lives on the registration. It cannot be preserved across
 * an unregister(); it has to be recreated. The stale row is pruned server-side
 * on the first 404/410.
 */

import { supabase } from "@/integrations/supabase/client";

const VAPID_CACHE_KEY = "warehouseWizard.push.vapidPublicKey";
const VAPID_TTL_MS = 24 * 60 * 60 * 1000;

/** Mirrors the constants in src/sw.ts — keep the two in step. */
const PUSH_ROTATION_CACHE = "ww-push-pending";
const PUSH_ROTATION_KEY = "/__ww_push_rotation";

export type PushSupport = "unsupported" | "supported";

export function pushSupport(): PushSupport {
  if (typeof window === "undefined") return "unsupported";
  if (!("serviceWorker" in navigator)) return "unsupported";
  if (!("PushManager" in window)) return "unsupported";
  if (!("Notification" in window)) return "unsupported";
  return "supported";
}

function readCachedKey(): string | null {
  try {
    const raw = window.localStorage.getItem(VAPID_CACHE_KEY);
    if (!raw) return null;
    const parsed = JSON.parse(raw) as { publicKey?: string; fetchedAt?: number };
    if (!parsed.publicKey || !parsed.fetchedAt) return null;
    if (Date.now() - parsed.fetchedAt > VAPID_TTL_MS) return null;
    return parsed.publicKey;
  } catch {
    return null;
  }
}

function writeCachedKey(publicKey: string) {
  try {
    window.localStorage.setItem(VAPID_CACHE_KEY, JSON.stringify({ publicKey, fetchedAt: Date.now() }));
  } catch {
    // Storage unavailable — we just re-fetch the key next time.
  }
}

function clearCachedKey() {
  try {
    window.localStorage.removeItem(VAPID_CACHE_KEY);
  } catch {
    // Nothing to do.
  }
}

export async function fetchVapidPublicKey(force = false): Promise<string | null> {
  if (!force) {
    const cached = readCachedKey();
    if (cached) return cached;
  }
  try {
    const { data, error } = await supabase.functions.invoke("push-notify", { body: { action: "config" } });
    if (error) return null;
    const publicKey = (data as { publicKey?: string | null } | null)?.publicKey;
    if (typeof publicKey !== "string" || !publicKey) return null;
    writeCachedKey(publicKey);
    return publicKey;
  } catch {
    return null;
  }
}

/**
 * VAPID keys travel as base64url; PushManager wants the raw bytes.
 *
 * Backed by an explicit ArrayBuffer so the result is Uint8Array<ArrayBuffer>:
 * since TS 5.7 a bare Uint8Array is generic over ArrayBufferLike, which
 * BufferSource will not accept.
 */
function urlBase64ToUint8Array(base64: string): Uint8Array<ArrayBuffer> {
  const padding = "=".repeat((4 - (base64.length % 4)) % 4);
  const normalised = (base64 + padding).replace(/-/g, "+").replace(/_/g, "/");
  const raw = window.atob(normalised);
  const output = new Uint8Array(new ArrayBuffer(raw.length));
  for (let i = 0; i < raw.length; i += 1) output[i] = raw.charCodeAt(i);
  return output;
}

function describeDevice(): string {
  const ua = navigator.userAgent;
  if (/Android/i.test(ua)) return "Android device";
  if (/iPhone|iPad|iPod/i.test(ua)) return "iOS device";
  if (/Windows/i.test(ua)) return "Windows desktop";
  if (/Mac OS X/i.test(ua)) return "Mac desktop";
  return "Browser";
}

async function saveSubscription(subscription: PushSubscription): Promise<boolean> {
  try {
    const { error } = await supabase.functions.invoke("push-notify", {
      body: {
        action: "subscribe",
        subscription: subscription.toJSON(),
        deviceLabel: describeDevice(),
      },
    });
    return !error;
  } catch {
    return false;
  }
}

/**
 * Drain a subscription the service worker parked during pushsubscriptionchange.
 *
 * A service worker has no Supabase session, so it cannot register the rotated
 * endpoint itself; it caches the handover and we complete it here.
 */
async function drainRotation(): Promise<void> {
  try {
    const cache = await caches.open(PUSH_ROTATION_CACHE);
    const stored = await cache.match(PUSH_ROTATION_KEY);
    if (!stored) return;
    const payload = (await stored.json()) as {
      oldEndpoint?: string | null;
      next?: { endpoint?: string; keys?: { p256dh?: string; auth?: string } } | null;
    };
    await cache.delete(PUSH_ROTATION_KEY);

    if (payload.oldEndpoint) {
      await supabase.functions
        .invoke("push-notify", { body: { action: "unsubscribe", endpoint: payload.oldEndpoint } })
        .catch(() => undefined);
    }
    if (payload.next?.endpoint && payload.next.keys?.p256dh && payload.next.keys.auth) {
      await supabase.functions
        .invoke("push-notify", { body: { action: "subscribe", subscription: payload.next, deviceLabel: describeDevice() } })
        .catch(() => undefined);
    }
  } catch {
    // Cache API unavailable or the entry was malformed — the fresh subscribe
    // below still gets this device back on the list.
  }
}

/**
 * Make sure this device has a live, registered subscription.
 *
 * Safe to call on every mount: an existing subscription is re-registered
 * (cheap upsert on the endpoint) rather than replaced.
 */
export async function ensurePushSubscription(): Promise<boolean> {
  if (pushSupport() === "unsupported") return false;
  if (Notification.permission !== "granted") return false;

  try {
    const registration = await navigator.serviceWorker.ready;
    if (!registration.pushManager) return false;

    await drainRotation();

    const existing = await registration.pushManager.getSubscription();
    if (existing) return await saveSubscription(existing);

    const publicKey = await fetchVapidPublicKey();
    if (!publicKey) return false;

    try {
      const subscription = await registration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: urlBase64ToUint8Array(publicKey),
      });
      return await saveSubscription(subscription);
    } catch (error) {
      // InvalidStateError / InvalidAccessError is the browser saying "you
      // already have a subscription under a DIFFERENT applicationServerKey" —
      // i.e. the VAPID key was rotated. Drop the stale one, re-fetch, retry
      // once. Without this branch a key rotation bricks push on every device
      // that was subscribed before it.
      const name = (error as { name?: string }).name;
      if (name !== "InvalidStateError" && name !== "InvalidAccessError") throw error;

      const stale = await registration.pushManager.getSubscription();
      if (stale) {
        await supabase.functions
          .invoke("push-notify", { body: { action: "unsubscribe", endpoint: stale.endpoint } })
          .catch(() => undefined);
        await stale.unsubscribe().catch(() => undefined);
      }
      clearCachedKey();
      const freshKey = await fetchVapidPublicKey(true);
      if (!freshKey) return false;
      const subscription = await registration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: urlBase64ToUint8Array(freshKey),
      });
      return await saveSubscription(subscription);
    }
  } catch {
    return false;
  }
}

/** Unsubscribe this device, both in the browser and server-side. */
export async function removePushSubscription(): Promise<boolean> {
  if (pushSupport() === "unsupported") return false;
  try {
    const registration = await navigator.serviceWorker.ready;
    const subscription = await registration.pushManager?.getSubscription();
    if (!subscription) return true;
    await supabase.functions
      .invoke("push-notify", { body: { action: "unsubscribe", endpoint: subscription.endpoint } })
      .catch(() => undefined);
    return await subscription.unsubscribe();
  } catch {
    return false;
  }
}

/** Whether this device currently holds a browser-level subscription. */
export async function hasPushSubscription(): Promise<boolean> {
  if (pushSupport() === "unsupported") return false;
  try {
    const registration = await navigator.serviceWorker.ready;
    return Boolean(await registration.pushManager?.getSubscription());
  } catch {
    return false;
  }
}
