project_id = "gxfvxmxplngvxdkpmxgw"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.badge-login]
    verify_jwt = false
  [functions.invite-user]
    verify_jwt = false
  [functions.copilot]
    verify_jwt = true
  [functions.send-notification-email]
    verify_jwt = true
  [functions.handle-email-events]
    verify_jwt = false
  [functions.preview-transactional-email]
    verify_jwt = false


[functions.copilot-transcribe]
enabled = true
verify_jwt = true
