project_id = "gxfvxmxplngvxdkpmxgw"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.badge-login]
    verify_jwt = false
  [functions.invite-user]
    verify_jwt = false
  [functions.copilot]
    verify_jwt = true
