#!/usr/bin/env bash
# Keeps the production and sandbox Lovable repos in step. See docs/REPO_SYNC.md.
#
#   scripts/repo-sync.sh status            both clones: what each side has that the other lacks
#   scripts/repo-sync.sh pull-prod         sandbox clone: bring production changes into the sandbox
#   scripts/repo-sync.sh promote [ref]     prod clone: bring sandbox work (default sandbox/main) into prod
#
# pull-prod and promote never touch main directly: they build a sync branch,
# repair environment-specific files, push it and open a PR.
set -euo pipefail

PROD_URL="https://github.com/classicitbb/warehouse-wizard.git"
SANDBOX_URL="https://github.com/classicitbb/warehousewizard-sandbox.git"
PROD_REF="gxfvxmxplngvxdkpmxgw"
SANDBOX_REF="emuyzymoadmzhnzjprjz"

# Files that belong to one environment and are always kept as they are on
# the receiving side.
KEEP_OURS=(
  .env
  src/integrations/supabase/client.ts
)

die() { printf 'error: %b
' "$*" >&2; exit 1; }

cd "$(git rev-parse --show-toplevel)"
origin_url="$(git remote get-url origin)"
case "$origin_url" in
  *warehousewizard-sandbox*) SIDE=sandbox OTHER_REMOTE=prod    OTHER_URL=$PROD_URL    OURS=$SANDBOX_REF THEIRS=$PROD_REF ;;
  *warehouse-wizard*)        SIDE=prod    OTHER_REMOTE=sandbox OTHER_URL=$SANDBOX_URL OURS=$PROD_REF    THEIRS=$SANDBOX_REF ;;
  *) die "origin ($origin_url) is neither the prod nor the sandbox repo" ;;
esac

git remote get-url "$OTHER_REMOTE" >/dev/null 2>&1 || git remote add "$OTHER_REMOTE" "$OTHER_URL"
git fetch -q origin
git fetch -q "$OTHER_REMOTE"

require_clean() {
  [ -z "$(git status --porcelain)" ] || die "working tree has uncommitted changes; commit or stash first"
}

# Undo the other environment's identity after a --no-commit merge.
repair_environment() {
  local f
  for f in "${KEEP_OURS[@]}"; do
    if git cat-file -e "HEAD:$f" 2>/dev/null; then
      git checkout HEAD -- "$f"
    fi
  done
  # Project ref baked into generated/config files (config.toml, mcp manifest,
  # mcp bundle). Migrations and docs are history and are left alone.
  local files
  files="$(git grep -l "$THEIRS" -- . ':!supabase/migrations' ':!docs' ':!scripts/repo-sync.sh' || true)"
  if [ -n "$files" ]; then
    echo "$files" | while read -r f; do sed -i "s/$THEIRS/$OURS/g" "$f"; git add "$f"; done
    echo "rewrote project ref in:"; echo "$files" | sed 's/^/  /'
  fi
  git add -A -- "${KEEP_OURS[@]}" 2>/dev/null || true
}

report_new_migrations() {
  local base="$1" incoming="$2" added
  added="$(git diff --name-only --diff-filter=A "$base" "$incoming" -- supabase/migrations || true)"
  if [ -n "$added" ]; then
    echo
    echo "New migrations arriving (must be applied to the $SIDE database after merge):"
    echo "$added" | sed 's/^/  /'
    if git grep -l "$THEIRS" "$incoming" -- $added >/dev/null 2>&1; then
      echo "  WARNING: at least one new migration references project $THEIRS - review before applying."
    fi
  fi
  local deleted
  deleted="$(git diff --name-only --diff-filter=D "$base" HEAD -- supabase/migrations || true)"
  [ -z "$deleted" ] || die "merge would delete migrations:\n$deleted"
}

sync_into() {
  local incoming="$1" prefix="$2" title="$3"
  require_clean
  local stamp branch base
  stamp="$(date +%Y%m%d-%H%M)"
  branch="$prefix/$stamp"
  git checkout -q -b "$branch" origin/main
  base="$(git merge-base HEAD "$incoming")"

  if ! git merge --no-ff --no-commit "$incoming" >/dev/null 2>&1; then
    repair_environment
    if [ -n "$(git diff --name-only --diff-filter=U)" ]; then
      echo "Merge conflicts to resolve on branch $branch:"
      git diff --name-only --diff-filter=U | sed 's/^/  /'
      echo "Resolve them, run 'git add' on each, then re-run: scripts/repo-sync.sh finish \"$title\""
      exit 2
    fi
  else
    repair_environment
  fi
  report_new_migrations "$base" "$incoming"
  finish "$title"
}

finish() {
  local title="$1" branch
  branch="$(git rev-parse --abbrev-ref HEAD)"
  git grep -q "$THEIRS" -- . ':!supabase/migrations' ':!docs' ':!scripts/repo-sync.sh' \
    && die "project ref $THEIRS still present; fix before committing"
  if git diff --cached --quiet && [ ! -f "$(git rev-parse --git-dir)/MERGE_HEAD" ]; then
    echo "Nothing to sync - already up to date."; git checkout -q main 2>/dev/null || true; git branch -D "$branch" >/dev/null; return
  fi
  git commit -q -m "$title" -m "Generated by scripts/repo-sync.sh" \
    -m "Co-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>"
  git push -q -u origin "$branch"
  gh pr create --base main --head "$branch" --title "$title" \
    --body "$(printf 'Automated sync via `scripts/repo-sync.sh`. Environment files (.env, supabase client, project refs) were kept for **%s**.\n\nAfter merging: apply any new migrations listed in the script output, then redeploy edge functions (see docs/REPO_SYNC.md).\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)' "$SIDE")"
}

cmd="${1:-status}"
case "$cmd" in
  status)
    p=$([ "$SIDE" = prod ] && echo origin/main || echo prod/main)
    s=$([ "$SIDE" = sandbox ] && echo origin/main || echo sandbox/main)
    echo "In prod, not yet in sandbox:"
    git log --oneline --no-merges "$s..$p" | sed 's/^/  /' | head -40
    echo "In sandbox, not yet in prod:"
    git log --oneline --no-merges "$p..$s" | sed 's/^/  /' | head -40
    ;;
  pull-prod)
    [ "$SIDE" = sandbox ] || die "run pull-prod from the sandbox clone"
    sync_into prod/main sync/from-prod "Sync production into sandbox"
    ;;
  promote)
    [ "$SIDE" = prod ] || die "run promote from the prod clone"
    ref="${2:-sandbox/main}"
    sync_into "$ref" promote/from-sandbox "Promote sandbox ($ref) to production"
    ;;
  finish)
    finish "${2:-Repo sync}"
    ;;
  *) die "unknown command: $cmd (status | pull-prod | promote [ref] | finish)" ;;
esac
