/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedShellRouteImport } from './routes/_authed/_shell'
import { Route as AuthedShellClientsRouteImport } from './routes/_authed/_shell/clients'
import { Route as AuthedShellCycleCountsRouteImport } from './routes/_authed/_shell/cycle-counts'
import { Route as AuthedShellDashboardRouteImport } from './routes/_authed/_shell/dashboard'
import { Route as AuthedShellEmailLogRouteImport } from './routes/_authed/_shell/email-log'
import { Route as AuthedShellHelpRouteImport } from './routes/_authed/_shell/help'
import { Route as AuthedShellInventorySearchRouteImport } from './routes/_authed/_shell/inventory-search'
import { Route as AuthedShellLocationMovesRouteImport } from './routes/_authed/_shell/location-moves'
import { Route as AuthedShellLocationsRouteImport } from './routes/_authed/_shell/locations'
import { Route as AuthedShellPackagingProfilesRouteImport } from './routes/_authed/_shell/packaging-profiles'
import { Route as AuthedShellPickListsRouteImport } from './routes/_authed/_shell/pick-lists'
import { Route as AuthedShellProductsRouteImport } from './routes/_authed/_shell/products'
import { Route as AuthedShellPutawayTasksRouteImport } from './routes/_authed/_shell/putaway-tasks'
import { Route as AuthedShellReceivingRouteImport } from './routes/_authed/_shell/receiving'
import { Route as AuthedShellReportsRouteImport } from './routes/_authed/_shell/reports'
import { Route as AuthedShellSettingsRouteImport } from './routes/_authed/_shell/settings'
import { Route as AuthedShellSetupWizardRouteImport } from './routes/_authed/_shell/setup-wizard'
import { Route as AuthedShellStatusRouteImport } from './routes/_authed/_shell/status'
import { Route as AuthedShellSystemLogRouteImport } from './routes/_authed/_shell/system-log'
import { Route as AuthedShellTransfersRouteImport } from './routes/_authed/_shell/transfers'
import { Route as AuthedShellUsersRouteImport } from './routes/_authed/_shell/users'
import { Route as AuthedShellWarehousesRouteImport } from './routes/_authed/_shell/warehouses'
import { Route as AuthedShellZonesRouteImport } from './routes/_authed/_shell/zones'
import { Route as AuthedInventoryBalanceIdRouteImport } from './routes/_authed/inventory.$balanceId'
import { Route as AuthedPickListsPickListIdRouteImport } from './routes/_authed/pick-lists.$pickListId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedShellRoute = AuthedShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedShellClientsRoute = AuthedShellClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthedShellRoute,
} as any)
const AuthedShellCycleCountsRoute = AuthedShellCycleCountsRouteImport.update({
  id: '/cycle-counts',
  path: '/cycle-counts',
  getParentRoute: () => AuthedShellRoute,
} as any)
const AuthedShellDashboardRoute = AuthedShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedShellRoute,
} as any)
const AuthedShellEmailLogRoute = AuthedShellEmailLogRouteImport.update({
  id: '/email-log',
  path: '/email-log',
  getParentRoute: () => AuthedShellRoute,
} as any)
const AuthedShellHelpRoute = AuthedShellHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthedShellRoute,
} as any)
const AuthedShellInventorySearchRoute =
  AuthedShellInventorySearchRouteImport.update({
    id: '/inventory-search',
    path: '/inventory-search',
    getParentRoute: () => AuthedShellRoute,
  } as any)
const AuthedShellLocationMovesRoute =
  AuthedShellLocationMovesRouteImport.update({
    id: '/location-moves',
    path: '/location-moves',
    getParentRoute: () => AuthedShellRoute,
  } as any)
const AuthedShellLocationsRoute = AuthedShellLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AuthedShellRoute,
} as any)
const AuthedShellPackagingProfilesRoute =
  AuthedShellPackagingProfilesRouteImport.update({
    id: '/packaging-profiles',
    path: '/packaging-profiles',
    getParentRoute: () => AuthedShellRoute,
  } as any)
const AuthedShellPickListsRoute = AuthedShellPickListsRouteImport.update({
  id: '/pick-lists',
  path: '/pick-lists',
  getParentRoute: () => AuthedShellRoute,
} as any)
const AuthedShellProductsRoute = AuthedShellProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthedShellRoute,
} as any)
const AuthedShellPutawayTasksRoute = AuthedShellPutawayTasksRouteImport.update({
  id: '/putaway-tasks',
  path: '/putaway-tasks',
  getParentRoute: () => AuthedShellRoute,
} as any)
const AuthedShellReceivingRoute = AuthedShellReceivingRouteImport.update({
  id: '/receiving',
  path: '/receiving',
  getParentRoute: () => AuthedShellRoute,
} as any)
const AuthedShellReportsRoute = AuthedShellReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthedShellRoute,
} as any)
const AuthedShellSettingsRoute = AuthedShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedShellRoute,
} as any)
const AuthedShellSetupWizardRoute = AuthedShellSetupWizardRouteImport.update({
  id: '/setup-wizard',
  path: '/setup-wizard',
  getParentRoute: () => AuthedShellRoute,
} as any)
const AuthedShellStatusRoute = AuthedShellStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => AuthedShellRoute,
} as any)
const AuthedShellSystemLogRoute = AuthedShellSystemLogRouteImport.update({
  id: '/system-log',
  path: '/system-log',
  getParentRoute: () => AuthedShellRoute,
} as any)
const AuthedShellTransfersRoute = AuthedShellTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AuthedShellRoute,
} as any)
const AuthedShellUsersRoute = AuthedShellUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedShellRoute,
} as any)
const AuthedShellWarehousesRoute = AuthedShellWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => AuthedShellRoute,
} as any)
const AuthedShellZonesRoute = AuthedShellZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => AuthedShellRoute,
} as any)
const AuthedInventoryBalanceIdRoute =
  AuthedInventoryBalanceIdRouteImport.update({
    id: '/inventory/$balanceId',
    path: '/inventory/$balanceId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedPickListsPickListIdRoute =
  AuthedPickListsPickListIdRouteImport.update({
    id: '/pick-lists/$pickListId',
    path: '/pick-lists/$pickListId',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/clients': typeof AuthedShellClientsRoute
  '/cycle-counts': typeof AuthedShellCycleCountsRoute
  '/dashboard': typeof AuthedShellDashboardRoute
  '/email-log': typeof AuthedShellEmailLogRoute
  '/help': typeof AuthedShellHelpRoute
  '/inventory-search': typeof AuthedShellInventorySearchRoute
  '/location-moves': typeof AuthedShellLocationMovesRoute
  '/locations': typeof AuthedShellLocationsRoute
  '/packaging-profiles': typeof AuthedShellPackagingProfilesRoute
  '/pick-lists': typeof AuthedShellPickListsRoute
  '/products': typeof AuthedShellProductsRoute
  '/putaway-tasks': typeof AuthedShellPutawayTasksRoute
  '/receiving': typeof AuthedShellReceivingRoute
  '/reports': typeof AuthedShellReportsRoute
  '/settings': typeof AuthedShellSettingsRoute
  '/setup-wizard': typeof AuthedShellSetupWizardRoute
  '/status': typeof AuthedShellStatusRoute
  '/system-log': typeof AuthedShellSystemLogRoute
  '/transfers': typeof AuthedShellTransfersRoute
  '/users': typeof AuthedShellUsersRoute
  '/warehouses': typeof AuthedShellWarehousesRoute
  '/zones': typeof AuthedShellZonesRoute
  '/inventory/$balanceId': typeof AuthedInventoryBalanceIdRoute
  '/pick-lists/$pickListId': typeof AuthedPickListsPickListIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/clients': typeof AuthedShellClientsRoute
  '/cycle-counts': typeof AuthedShellCycleCountsRoute
  '/dashboard': typeof AuthedShellDashboardRoute
  '/email-log': typeof AuthedShellEmailLogRoute
  '/help': typeof AuthedShellHelpRoute
  '/inventory-search': typeof AuthedShellInventorySearchRoute
  '/location-moves': typeof AuthedShellLocationMovesRoute
  '/locations': typeof AuthedShellLocationsRoute
  '/packaging-profiles': typeof AuthedShellPackagingProfilesRoute
  '/pick-lists': typeof AuthedShellPickListsRoute
  '/products': typeof AuthedShellProductsRoute
  '/putaway-tasks': typeof AuthedShellPutawayTasksRoute
  '/receiving': typeof AuthedShellReceivingRoute
  '/reports': typeof AuthedShellReportsRoute
  '/settings': typeof AuthedShellSettingsRoute
  '/setup-wizard': typeof AuthedShellSetupWizardRoute
  '/status': typeof AuthedShellStatusRoute
  '/system-log': typeof AuthedShellSystemLogRoute
  '/transfers': typeof AuthedShellTransfersRoute
  '/users': typeof AuthedShellUsersRoute
  '/warehouses': typeof AuthedShellWarehousesRoute
  '/zones': typeof AuthedShellZonesRoute
  '/inventory/$balanceId': typeof AuthedInventoryBalanceIdRoute
  '/pick-lists/$pickListId': typeof AuthedPickListsPickListIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/_shell': typeof AuthedShellRouteWithChildren
  '/_authed/_shell/clients': typeof AuthedShellClientsRoute
  '/_authed/_shell/cycle-counts': typeof AuthedShellCycleCountsRoute
  '/_authed/_shell/dashboard': typeof AuthedShellDashboardRoute
  '/_authed/_shell/email-log': typeof AuthedShellEmailLogRoute
  '/_authed/_shell/help': typeof AuthedShellHelpRoute
  '/_authed/_shell/inventory-search': typeof AuthedShellInventorySearchRoute
  '/_authed/_shell/location-moves': typeof AuthedShellLocationMovesRoute
  '/_authed/_shell/locations': typeof AuthedShellLocationsRoute
  '/_authed/_shell/packaging-profiles': typeof AuthedShellPackagingProfilesRoute
  '/_authed/_shell/pick-lists': typeof AuthedShellPickListsRoute
  '/_authed/_shell/products': typeof AuthedShellProductsRoute
  '/_authed/_shell/putaway-tasks': typeof AuthedShellPutawayTasksRoute
  '/_authed/_shell/receiving': typeof AuthedShellReceivingRoute
  '/_authed/_shell/reports': typeof AuthedShellReportsRoute
  '/_authed/_shell/settings': typeof AuthedShellSettingsRoute
  '/_authed/_shell/setup-wizard': typeof AuthedShellSetupWizardRoute
  '/_authed/_shell/status': typeof AuthedShellStatusRoute
  '/_authed/_shell/system-log': typeof AuthedShellSystemLogRoute
  '/_authed/_shell/transfers': typeof AuthedShellTransfersRoute
  '/_authed/_shell/users': typeof AuthedShellUsersRoute
  '/_authed/_shell/warehouses': typeof AuthedShellWarehousesRoute
  '/_authed/_shell/zones': typeof AuthedShellZonesRoute
  '/_authed/inventory/$balanceId': typeof AuthedInventoryBalanceIdRoute
  '/_authed/pick-lists/$pickListId': typeof AuthedPickListsPickListIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/clients'
    | '/cycle-counts'
    | '/dashboard'
    | '/email-log'
    | '/help'
    | '/inventory-search'
    | '/location-moves'
    | '/locations'
    | '/packaging-profiles'
    | '/pick-lists'
    | '/products'
    | '/putaway-tasks'
    | '/receiving'
    | '/reports'
    | '/settings'
    | '/setup-wizard'
    | '/status'
    | '/system-log'
    | '/transfers'
    | '/users'
    | '/warehouses'
    | '/zones'
    | '/inventory/$balanceId'
    | '/pick-lists/$pickListId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/clients'
    | '/cycle-counts'
    | '/dashboard'
    | '/email-log'
    | '/help'
    | '/inventory-search'
    | '/location-moves'
    | '/locations'
    | '/packaging-profiles'
    | '/pick-lists'
    | '/products'
    | '/putaway-tasks'
    | '/receiving'
    | '/reports'
    | '/settings'
    | '/setup-wizard'
    | '/status'
    | '/system-log'
    | '/transfers'
    | '/users'
    | '/warehouses'
    | '/zones'
    | '/inventory/$balanceId'
    | '/pick-lists/$pickListId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/_shell'
    | '/_authed/_shell/clients'
    | '/_authed/_shell/cycle-counts'
    | '/_authed/_shell/dashboard'
    | '/_authed/_shell/email-log'
    | '/_authed/_shell/help'
    | '/_authed/_shell/inventory-search'
    | '/_authed/_shell/location-moves'
    | '/_authed/_shell/locations'
    | '/_authed/_shell/packaging-profiles'
    | '/_authed/_shell/pick-lists'
    | '/_authed/_shell/products'
    | '/_authed/_shell/putaway-tasks'
    | '/_authed/_shell/receiving'
    | '/_authed/_shell/reports'
    | '/_authed/_shell/settings'
    | '/_authed/_shell/setup-wizard'
    | '/_authed/_shell/status'
    | '/_authed/_shell/system-log'
    | '/_authed/_shell/transfers'
    | '/_authed/_shell/users'
    | '/_authed/_shell/warehouses'
    | '/_authed/_shell/zones'
    | '/_authed/inventory/$balanceId'
    | '/_authed/pick-lists/$pickListId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_shell': {
      id: '/_authed/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedShellRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_shell/clients': {
      id: '/_authed/_shell/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthedShellClientsRouteImport
      parentRoute: typeof AuthedShellRoute
    }
    '/_authed/_shell/cycle-counts': {
      id: '/_authed/_shell/cycle-counts'
      path: '/cycle-counts'
      fullPath: '/cycle-counts'
      preLoaderRoute: typeof AuthedShellCycleCountsRouteImport
      parentRoute: typeof AuthedShellRoute
    }
    '/_authed/_shell/dashboard': {
      id: '/_authed/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedShellDashboardRouteImport
      parentRoute: typeof AuthedShellRoute
    }
    '/_authed/_shell/email-log': {
      id: '/_authed/_shell/email-log'
      path: '/email-log'
      fullPath: '/email-log'
      preLoaderRoute: typeof AuthedShellEmailLogRouteImport
      parentRoute: typeof AuthedShellRoute
    }
    '/_authed/_shell/help': {
      id: '/_authed/_shell/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthedShellHelpRouteImport
      parentRoute: typeof AuthedShellRoute
    }
    '/_authed/_shell/inventory-search': {
      id: '/_authed/_shell/inventory-search'
      path: '/inventory-search'
      fullPath: '/inventory-search'
      preLoaderRoute: typeof AuthedShellInventorySearchRouteImport
      parentRoute: typeof AuthedShellRoute
    }
    '/_authed/_shell/location-moves': {
      id: '/_authed/_shell/location-moves'
      path: '/location-moves'
      fullPath: '/location-moves'
      preLoaderRoute: typeof AuthedShellLocationMovesRouteImport
      parentRoute: typeof AuthedShellRoute
    }
    '/_authed/_shell/locations': {
      id: '/_authed/_shell/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AuthedShellLocationsRouteImport
      parentRoute: typeof AuthedShellRoute
    }
    '/_authed/_shell/packaging-profiles': {
      id: '/_authed/_shell/packaging-profiles'
      path: '/packaging-profiles'
      fullPath: '/packaging-profiles'
      preLoaderRoute: typeof AuthedShellPackagingProfilesRouteImport
      parentRoute: typeof AuthedShellRoute
    }
    '/_authed/_shell/pick-lists': {
      id: '/_authed/_shell/pick-lists'
      path: '/pick-lists'
      fullPath: '/pick-lists'
      preLoaderRoute: typeof AuthedShellPickListsRouteImport
      parentRoute: typeof AuthedShellRoute
    }
    '/_authed/_shell/products': {
      id: '/_authed/_shell/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthedShellProductsRouteImport
      parentRoute: typeof AuthedShellRoute
    }
    '/_authed/_shell/putaway-tasks': {
      id: '/_authed/_shell/putaway-tasks'
      path: '/putaway-tasks'
      fullPath: '/putaway-tasks'
      preLoaderRoute: typeof AuthedShellPutawayTasksRouteImport
      parentRoute: typeof AuthedShellRoute
    }
    '/_authed/_shell/receiving': {
      id: '/_authed/_shell/receiving'
      path: '/receiving'
      fullPath: '/receiving'
      preLoaderRoute: typeof AuthedShellReceivingRouteImport
      parentRoute: typeof AuthedShellRoute
    }
    '/_authed/_shell/reports': {
      id: '/_authed/_shell/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthedShellReportsRouteImport
      parentRoute: typeof AuthedShellRoute
    }
    '/_authed/_shell/settings': {
      id: '/_authed/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedShellSettingsRouteImport
      parentRoute: typeof AuthedShellRoute
    }
    '/_authed/_shell/setup-wizard': {
      id: '/_authed/_shell/setup-wizard'
      path: '/setup-wizard'
      fullPath: '/setup-wizard'
      preLoaderRoute: typeof AuthedShellSetupWizardRouteImport
      parentRoute: typeof AuthedShellRoute
    }
    '/_authed/_shell/status': {
      id: '/_authed/_shell/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof AuthedShellStatusRouteImport
      parentRoute: typeof AuthedShellRoute
    }
    '/_authed/_shell/system-log': {
      id: '/_authed/_shell/system-log'
      path: '/system-log'
      fullPath: '/system-log'
      preLoaderRoute: typeof AuthedShellSystemLogRouteImport
      parentRoute: typeof AuthedShellRoute
    }
    '/_authed/_shell/transfers': {
      id: '/_authed/_shell/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof AuthedShellTransfersRouteImport
      parentRoute: typeof AuthedShellRoute
    }
    '/_authed/_shell/users': {
      id: '/_authed/_shell/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthedShellUsersRouteImport
      parentRoute: typeof AuthedShellRoute
    }
    '/_authed/_shell/warehouses': {
      id: '/_authed/_shell/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof AuthedShellWarehousesRouteImport
      parentRoute: typeof AuthedShellRoute
    }
    '/_authed/_shell/zones': {
      id: '/_authed/_shell/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof AuthedShellZonesRouteImport
      parentRoute: typeof AuthedShellRoute
    }
    '/_authed/inventory/$balanceId': {
      id: '/_authed/inventory/$balanceId'
      path: '/inventory/$balanceId'
      fullPath: '/inventory/$balanceId'
      preLoaderRoute: typeof AuthedInventoryBalanceIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/pick-lists/$pickListId': {
      id: '/_authed/pick-lists/$pickListId'
      path: '/pick-lists/$pickListId'
      fullPath: '/pick-lists/$pickListId'
      preLoaderRoute: typeof AuthedPickListsPickListIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedShellRouteChildren {
  AuthedShellClientsRoute: typeof AuthedShellClientsRoute
  AuthedShellCycleCountsRoute: typeof AuthedShellCycleCountsRoute
  AuthedShellDashboardRoute: typeof AuthedShellDashboardRoute
  AuthedShellEmailLogRoute: typeof AuthedShellEmailLogRoute
  AuthedShellHelpRoute: typeof AuthedShellHelpRoute
  AuthedShellInventorySearchRoute: typeof AuthedShellInventorySearchRoute
  AuthedShellLocationMovesRoute: typeof AuthedShellLocationMovesRoute
  AuthedShellLocationsRoute: typeof AuthedShellLocationsRoute
  AuthedShellPackagingProfilesRoute: typeof AuthedShellPackagingProfilesRoute
  AuthedShellPickListsRoute: typeof AuthedShellPickListsRoute
  AuthedShellProductsRoute: typeof AuthedShellProductsRoute
  AuthedShellPutawayTasksRoute: typeof AuthedShellPutawayTasksRoute
  AuthedShellReceivingRoute: typeof AuthedShellReceivingRoute
  AuthedShellReportsRoute: typeof AuthedShellReportsRoute
  AuthedShellSettingsRoute: typeof AuthedShellSettingsRoute
  AuthedShellSetupWizardRoute: typeof AuthedShellSetupWizardRoute
  AuthedShellStatusRoute: typeof AuthedShellStatusRoute
  AuthedShellSystemLogRoute: typeof AuthedShellSystemLogRoute
  AuthedShellTransfersRoute: typeof AuthedShellTransfersRoute
  AuthedShellUsersRoute: typeof AuthedShellUsersRoute
  AuthedShellWarehousesRoute: typeof AuthedShellWarehousesRoute
  AuthedShellZonesRoute: typeof AuthedShellZonesRoute
}

const AuthedShellRouteChildren: AuthedShellRouteChildren = {
  AuthedShellClientsRoute: AuthedShellClientsRoute,
  AuthedShellCycleCountsRoute: AuthedShellCycleCountsRoute,
  AuthedShellDashboardRoute: AuthedShellDashboardRoute,
  AuthedShellEmailLogRoute: AuthedShellEmailLogRoute,
  AuthedShellHelpRoute: AuthedShellHelpRoute,
  AuthedShellInventorySearchRoute: AuthedShellInventorySearchRoute,
  AuthedShellLocationMovesRoute: AuthedShellLocationMovesRoute,
  AuthedShellLocationsRoute: AuthedShellLocationsRoute,
  AuthedShellPackagingProfilesRoute: AuthedShellPackagingProfilesRoute,
  AuthedShellPickListsRoute: AuthedShellPickListsRoute,
  AuthedShellProductsRoute: AuthedShellProductsRoute,
  AuthedShellPutawayTasksRoute: AuthedShellPutawayTasksRoute,
  AuthedShellReceivingRoute: AuthedShellReceivingRoute,
  AuthedShellReportsRoute: AuthedShellReportsRoute,
  AuthedShellSettingsRoute: AuthedShellSettingsRoute,
  AuthedShellSetupWizardRoute: AuthedShellSetupWizardRoute,
  AuthedShellStatusRoute: AuthedShellStatusRoute,
  AuthedShellSystemLogRoute: AuthedShellSystemLogRoute,
  AuthedShellTransfersRoute: AuthedShellTransfersRoute,
  AuthedShellUsersRoute: AuthedShellUsersRoute,
  AuthedShellWarehousesRoute: AuthedShellWarehousesRoute,
  AuthedShellZonesRoute: AuthedShellZonesRoute,
}

const AuthedShellRouteWithChildren = AuthedShellRoute._addFileChildren(
  AuthedShellRouteChildren,
)

interface AuthedRouteChildren {
  AuthedShellRoute: typeof AuthedShellRouteWithChildren
  AuthedInventoryBalanceIdRoute: typeof AuthedInventoryBalanceIdRoute
  AuthedPickListsPickListIdRoute: typeof AuthedPickListsPickListIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedShellRoute: AuthedShellRouteWithChildren,
  AuthedInventoryBalanceIdRoute: AuthedInventoryBalanceIdRoute,
  AuthedPickListsPickListIdRoute: AuthedPickListsPickListIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
