// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.0";

// src/lib/mcp/tools/list-warehouses.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/tools/_supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.106.2";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function firstEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseUrl() {
  const url = firstEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL is required");
  return url;
}
function supabaseKey() {
  const direct = firstEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find(
          (v) => typeof v === "string" && v.trim().startsWith("sb_publishable_")
        );
        if (key) return key.trim();
      }
    } catch {
    }
  }
  const legacy = firstEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("Supabase publishable/anon key is required");
}
function supabaseForUser(ctx) {
  return createClient(supabaseUrl(), supabaseKey(), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-warehouses.ts
var list_warehouses_default = defineTool({
  name: "list_warehouses",
  title: "List warehouses",
  description: "List warehouses visible to the signed-in user.",
  inputSchema: {
    includeHidden: z.boolean().optional().describe("Include hidden warehouses (default false).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ includeHidden }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser(ctx).from("warehouses").select("id, code, name, city, country, has_cool_zone, active").order("code");
    if (!includeHidden) q = q.eq("is_hidden", false);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-products.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z2 } from "npm:zod@^3.25.76";
function escapePostgrestOrValue(value) {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}
var search_products_default = defineTool2({
  name: "search_products",
  title: "Search products",
  description: "Search the product catalog by SKU, barcode, or name (case-insensitive substring match).",
  inputSchema: {
    query: z2.string().trim().min(1).describe("SKU, barcode, or product name substring."),
    limit: z2.number().int().min(1).max(100).optional().describe("Max rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const term = escapePostgrestOrValue(`%${query}%`);
    const { data, error } = await supabaseForUser(ctx).from("products").select("id, sku, barcode, name, description, temperature_requirement, active").or(`sku.ilike.${term},barcode.ilike.${term},name.ilike.${term}`).eq("active", true).limit(limit ?? 25);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { rows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/inventory-summary.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z3 } from "npm:zod@^3.25.76";
var inventory_summary_default = defineTool3({
  name: "inventory_summary",
  title: "Inventory summary for a product",
  description: "Return current inventory balances (quantity, available, reserved) for a product by SKU, across visible warehouses and locations.",
  inputSchema: {
    sku: z3.string().trim().min(1).describe("Exact product SKU to look up."),
    limit: z3.number().int().min(1).max(200).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ sku, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data: product, error: prodErr } = await sb.from("products").select("id, sku, name").eq("sku", sku).maybeSingle();
    if (prodErr) return { content: [{ type: "text", text: prodErr.message }], isError: true };
    if (!product) return { content: [{ type: "text", text: `No product found with SKU ${sku}` }] };
    const { data, error } = await sb.from("inventory_balances").select(
      "id, quantity, available_quantity, reserved_quantity, held_quantity, damaged_quantity, status, expiry_date, warehouses(code, name), locations(code)"
    ).eq("product_id", product.id).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).map((r) => ({
      warehouse: r.warehouses?.code ?? null,
      location: r.locations?.code ?? null,
      status: r.status,
      quantity: r.quantity,
      available: r.available_quantity,
      reserved: r.reserved_quantity,
      held: r.held_quantity,
      damaged: r.damaged_quantity,
      expiry_date: r.expiry_date
    }));
    const total = rows.reduce((s, r) => s + (Number(r.quantity) || 0), 0);
    return {
      content: [
        {
          type: "text",
          text: JSON.stringify({ product, total_quantity: total, rows }, null, 2)
        }
      ],
      structuredContent: { product, total_quantity: total, rows }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "gxfvxmxplngvxdkpmxgw";
var mcp_default = defineMcp({
  name: "warehouse-wizard-mcp",
  title: "Warehouse Wizard MCP",
  version: "0.1.0",
  instructions: "Read-only tools for the Warehouse Wizard WMS. Use `list_warehouses` to see warehouses, `search_products` to find a product by SKU/barcode/name, and `inventory_summary` to see on-hand quantities per warehouse/location for a product. All calls act as the signed-in user under the app's RLS policies.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_warehouses_default, search_products_default, inventory_summary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
